env:
  es6: true
  browser: true
  node: true
  amd: true
  commonjs: true
  jasmine: true
extends: standard
globals:
  _: false
  Regular: false
  restate: false
  RegularStrap: false
  process: false